# Generated by Django 2.1.5 on 2019-02-06 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Descricao')),
                ('sobrenome', models.CharField(max_length=1, verbose_name='Sobrenome')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('cep', models.CharField(max_length=100, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilProfissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Descricao')),
                ('sobrenome', models.CharField(max_length=1, verbose_name='Sobrenome')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('cep', models.CharField(max_length=100, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='SubTopicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Subtópicos')),
            ],
        ),
        migrations.CreateModel(
            name='Topicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Tópicos')),
            ],
        ),
        migrations.AddField(
            model_name='perfilprofissional',
            name='subtopico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.SubTopicos'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.Topicos'),
        ),
    ]
