# Generated by Django 2.1.3 on 2019-02-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_auto_20190207_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilempresa',
            name='telefone',
            field=models.CharField(max_length=100, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='perfilprofissional',
            name='telefone',
            field=models.CharField(max_length=100, verbose_name='Telefone'),
        ),
    ]
