# Generated by Django 2.1.3 on 2019-02-07 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0005_auto_20190207_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilempresa',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='perfilprofissional',
            name='id_user',
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilprofissional',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
