# Generated by Django 2.1.4 on 2018-12-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='descricao',
            field=models.TextField(verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor'),
        ),
    ]
